# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11p7O3xlW7o2ORpX8VO3SVP1MwJF2Sc30
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

np.random.seed(42)
n_samples = 1000
n_features = 5

X = np.random.rand(n_samples, n_features)
y = np.random.randint(4, size=n_samples)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)